/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import modelo.Conexao;
import controle.EmprestimoControle;
import javax.swing.*;
import javax.swing.table.DefaultTableModel; // Importação necessária
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

public class TelaLista extends JFrame {
    private JTable tabelaEmprestimos;
    private JScrollPane scrollPane;
    private JButton btnEditar;
    private JButton btnExcluir;

    public TelaLista() {
        setTitle("Listagem de Empréstimos");
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        setLayout(new BorderLayout());

        // Criar os botões
        JPanel painelBotoes = new JPanel();
        btnEditar = new JButton("Editar");
        btnExcluir = new JButton("Excluir");

        painelBotoes.add(btnEditar);
        painelBotoes.add(btnExcluir);
        add(painelBotoes, BorderLayout.NORTH);

        // Criar a tabela
        tabelaEmprestimos = new JTable();
        scrollPane = new JScrollPane(tabelaEmprestimos);
        add(scrollPane, BorderLayout.CENTER);

        // Carregar os dados
        carregarTabelaEmprestimos();

        // Ação do botão editar
        btnEditar.addActionListener(e -> editarEmprestimo());

        // Ação do botão excluir
        btnExcluir.addActionListener(e -> excluirEmprestimo());
    }

    private void carregarTabelaEmprestimos() {
        try {
            EmprestimoControle emprestimoControle = new EmprestimoControle();
            
            // Obter a lista de empréstimos
            ArrayList<String[]> listaEmprestimos = emprestimoControle.listarEmprestimos();

            // Definir as colunas para a tabela
            String[] colunas = {"ID", "Livro", "Usuário", "Data Empréstimo", "Data Devolução"};
            DefaultTableModel model = new DefaultTableModel(colunas, 0);

            // Preencher o modelo da tabela com os dados
            for (String[] emprestimo : listaEmprestimos) {
                model.addRow(emprestimo);
            }

            // Associar o modelo à tabela
            tabelaEmprestimos.setModel(model);

        } catch (Exception e) {  // Usando exceção genérica para capturar qualquer erro
            JOptionPane.showMessageDialog(this, "Erro ao carregar os dados dos empréstimos: " + e.getMessage());
        }
    }

    private void editarEmprestimo() {
        int linhaSelecionada = tabelaEmprestimos.getSelectedRow();
        if (linhaSelecionada != -1) {
            String idEmprestimo = (String) tabelaEmprestimos.getValueAt(linhaSelecionada, 0);
            JOptionPane.showMessageDialog(this, "Editar Empréstimo ID: " + idEmprestimo);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo para editar.");
        }
    }

    private void excluirEmprestimo() {
        int linhaSelecionada = tabelaEmprestimos.getSelectedRow();
        if (linhaSelecionada != -1) {
            String idEmprestimo = (String) tabelaEmprestimos.getValueAt(linhaSelecionada, 0);
            JOptionPane.showMessageDialog(this, "Excluir Empréstimo ID: " + idEmprestimo);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo para excluir.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBeditar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBeditar.setBackground(new java.awt.Color(102, 204, 255));
        jBeditar.setForeground(new java.awt.Color(255, 255, 255));
        jBeditar.setText("Editar");

        jBexcluir.setBackground(new java.awt.Color(102, 204, 255));
        jBexcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBexcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jBeditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBexcluir)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBeditar)
                    .addComponent(jBexcluir))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaLista().setVisible(true);  // A exceção SQLException será propagada aqui
                } catch (Exception e) {
                    e.printStackTrace();  // Aqui você pode fazer o que preferir com a exceção
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    // End of variables declaration//GEN-END:variables
}
